- name: Deploying Apache Web Server on AWS EC2 instance
  hosts: your_EC2_instance
  become: yes
  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: present

    - name: Start httpd service
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Copy website content
      copy:
        src: index.html
        dest: /var/www/html
